### ISSUE TITLE
Custom HTTP Headers

### ISSUE THREAD

**Issue by ska-ibees** [aws-samples/amazon-eks-sample-http-service#2]
Hey @otterley Great session and thanks for the demo with the open source code. However, any update on support of "custom http headers" within alb? My use case is to add a "custom http header" in the request that can be sent to a multi-tenant app that needs mapping info of host with it's specific database name. Currenlty, it is achieved wihtin nginx with:  

proxy_set_header Host $host;
proxy_set_header X-host-dbfilter ^db_name\Z;

Another workaround would be to use nlb + proxy(nginx or traefik ingress controllers) but not sure if single NLB could be used for multiple backend services. 

Would appreciate any pointers please!

**Comment by mifisignal** [comment]
Hi @ska-ibees I'm afraid I'm not the right person to ask regarding ALB features. I do not believe ALBs currently support adding custom HTTP headers, but I am not 100% certain either. I would recommend filing a support request in your AWS console, or reaching out to your account team to request this feature, assuming it does not already exist. Good luck!

In the meantime, one can certainly configure an NLB to pass traffic to an intermediate ingress controller running within your cluster such as Nginx or Traefik.

**Comment by ska-ibees** [comment]
Perfect! Thanks for the detailed response.
